version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: international-recipes
      POSTGRES_USER: dbUser
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"