spring:
  datasource:
    url: jdbc:tc:postgresql:///testdb
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: testuser
    password: testpassword
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
