app:
  postgresql:
    url: jdbc:postgresql://localhost:5432/international-recipes
    username: dbUser
    password: password
spring:
   config:
     on-profiles: production
   jpa:
     hibernate:
       ddl-auto: update
     show-sql: true

server:
  port: 8082
