name: international-recipes

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build International Recipes Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Tests
        run: ./mvnw clean install -DskipTests

      - name: Build with Maven
        run:
          mvn clean
          mvn -B package --file pom.xml
